### ISSUE TITLE
output

### ISSUE THREAD

**Issue by LukeJBullard** [keplersj/singingSiri#3]
I am curious what audio this will output. Does it actually change the tune of the TTS output to match the song, or is it pretty much reading the lyrics with TTS? I read the code and am not sure if there is some iOS API call I missed or something. I would have tested but I don't have OSX so no xcode.

**Comment by keplersj** [comment]
This was an add-on of sorts to an iOS modification called SiriExtensions, which was really only prominent in iOS 5 and iOS 6. Being my first experience in programming all it really did was make the system TTS read the lyrics to a pre-programmed song in order. I've thought about going back and seeing how this could be made better but Siri modifications just aren't cool anymore.
